-- Verify reveal_monitoring_tables:data_integrity_validation_functions on pg

BEGIN;

SET search_path TO :"schema",public;

SELECT has_function_privilege(:'schema' || '.orphaned_jurisdictions(integer)', 'execute');
SELECT has_function_privilege(:'schema' || '.missing_goal_actions(integer)', 'execute');
SELECT has_function_privilege(:'schema' || '.missing_subject_tasks(integer)', 'execute');

-- TODO: Add tests for the above functions i.e. do they actually work as advertised?

ROLLBACK;
