-- Verify reveal_monitoring_tables:failed_flowfiles on pg

BEGIN;

-- this table is deleted in a later migration so this is not needed
-- and will break tests if activated

-- SET search_path TO :"schema",public;

-- SELECT id, type, last_updated
-- FROM failed_flowfiles
-- WHERE FALSE;

-- -- check primary key
-- SELECT 1/COUNT(*)
-- FROM pg_catalog.pg_constraint
-- WHERE
-- conname = 'failed_flowfiles_pkey'
-- AND contype = 'p'
-- AND conkey @> '{1, 2}';

ROLLBACK;
