-- Revert reveal_raw_tables:add_serial_id from pg

BEGIN;
 
SET search_path TO :"schema",public;

ALTER TABLE raw_clients
DROP COLUMN serial_id;

ALTER TABLE raw_jurisdictions
DROP COLUMN serial_id;

ALTER TABLE raw_locations
DROP COLUMN serial_id;

ALTER TABLE raw_plans
DROP COLUMN serial_id;

ALTER TABLE raw_settings
DROP COLUMN serial_id;

ALTER TABLE raw_tasks
DROP COLUMN serial_id;

ALTER TABLE raw_events
DROP COLUMN serial_id;

COMMIT;
