-- Revert reveal_irs_zambia_2019:structure_geo_hierarchy_triggers from pg

BEGIN;

SET search_path TO :"schema",public;

DROP TRIGGER IF EXISTS process_structure_geo_hierarchy_trigger
  ON structures;

DROP TRIGGER IF EXISTS jurisdiction_create_structure_geo_hierarchy_trigger
  ON jurisdictions;

DROP FUNCTION IF EXISTS process_structure_geo_hierarchy();

DROP FUNCTION IF EXISTS jurisdiction_create_structure_geo_hierarchy();

COMMIT;
